"""empty message

Revision ID: 6a304e82ef45
Revises: 
Create Date: 2023-11-26 16:17:07.431368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a304e82ef45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airp',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('air_pressure', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('humid',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('light',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('light', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temp',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temp')
    op.drop_table('light')
    op.drop_table('humid')
    op.drop_table('airp')
    # ### end Alembic commands ###
